'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18449
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("D_RAT.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- phpMyAdmin SQL Dump
        '''-- version 4.1.6
        '''-- http://www.phpmyadmin.net
        '''--
        '''-- Client :  127.0.0.1
        '''-- Généré le :  Mer 16 Juillet 2014 à 20:18
        '''-- Version du serveur :  5.6.16
        '''-- Version de PHP :  5.5.9
        '''
        '''SET SQL_MODE = &quot;NO_AUTO_VALUE_ON_ZERO&quot;;
        '''SET time_zone = &quot;+00:00&quot;;
        '''
        '''
        '''/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
        '''/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
        '''/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
        '''/*!40101 SET NAMES utf8 */;
        '''
        '''--
        '''-- Base de do [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DB() As String
            Get
                Return ResourceManager.GetString("DB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?php
        '''$con=mysqli_connect(&quot;|H|&quot;,&quot;|U|&quot;,&quot;|P|&quot;,&quot;|DB|&quot;);
        '''// Check connection
        '''if (mysqli_connect_errno()) {
        '''  echo &quot;Failed to connect to MySQL: &quot; . mysqli_connect_error();
        '''}
        '''$result = mysqli_query($con,&quot;SELECT * FROM IP_updater&quot;);
        '''while($row = mysqli_fetch_array($result)) {
        '''  echo $row[&apos;New_IP&apos;];
        '''  header(&quot;Location: http://&quot; . $row[&apos;New_IP&apos;]);
        '''}
        '''mysqli_close($con);
        '''?&gt;.
        '''</summary>
        Friend ReadOnly Property PHP_Page() As String
            Get
                Return ResourceManager.GetString("PHP_Page", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
