namespace NINGALINET
{
	// Token: 0x0200000C RID: 12
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class FrmBuy : global::System.Windows.Forms.Form
	{
		// Token: 0x060002C6 RID: 710 RVA: 0x0001CF4C File Offset: 0x0001B14C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060002C7 RID: 711 RVA: 0x0001CF90 File Offset: 0x0001B190
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::NINGALINET.FrmBuy));
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.Label22 = new global::System.Windows.Forms.Label();
			this.Label23 = new global::System.Windows.Forms.Label();
			this.Panel6 = new global::System.Windows.Forms.Panel();
			this.Label26 = new global::System.Windows.Forms.Label();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.Button9 = new global::System.Windows.Forms.Button();
			this.Button10 = new global::System.Windows.Forms.Button();
			this.Button17 = new global::System.Windows.Forms.Button();
			this.Button18 = new global::System.Windows.Forms.Button();
			this.Label27 = new global::System.Windows.Forms.Label();
			this.Panel7 = new global::System.Windows.Forms.Panel();
			this.Label28 = new global::System.Windows.Forms.Label();
			this.Button25 = new global::System.Windows.Forms.Button();
			this.Button27 = new global::System.Windows.Forms.Button();
			this.Button28 = new global::System.Windows.Forms.Button();
			this.Button29 = new global::System.Windows.Forms.Button();
			this.Button30 = new global::System.Windows.Forms.Button();
			this.Label29 = new global::System.Windows.Forms.Label();
			this.Panel8 = new global::System.Windows.Forms.Panel();
			this.Label30 = new global::System.Windows.Forms.Label();
			this.Button31 = new global::System.Windows.Forms.Button();
			this.Button33 = new global::System.Windows.Forms.Button();
			this.Button34 = new global::System.Windows.Forms.Button();
			this.Button35 = new global::System.Windows.Forms.Button();
			this.Button36 = new global::System.Windows.Forms.Button();
			this.Label31 = new global::System.Windows.Forms.Label();
			this.Label32 = new global::System.Windows.Forms.Label();
			this.Label33 = new global::System.Windows.Forms.Label();
			this.Label34 = new global::System.Windows.Forms.Label();
			this.GroupPanelBox1 = new global::NINGALINET.GroupPanelBox();
			this.RichTextBox1 = new global::System.Windows.Forms.RichTextBox();
			this.RadioButton1 = new global::System.Windows.Forms.RadioButton();
			this.RadioButton2 = new global::System.Windows.Forms.RadioButton();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			this.Panel6.SuspendLayout();
			this.Panel7.SuspendLayout();
			this.Panel8.SuspendLayout();
			this.GroupPanelBox1.SuspendLayout();
			this.SuspendLayout();
			this.PictureBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			global::System.Windows.Forms.Control arg_218_0 = this.PictureBox2;
			global::System.Drawing.Point location = new global::System.Drawing.Point(132, 323);
			arg_218_0.Location = location;
			this.PictureBox2.Name = "PictureBox2";
			global::System.Windows.Forms.Control arg_23F_0 = this.PictureBox2;
			global::System.Drawing.Size size = new global::System.Drawing.Size(16, 17);
			arg_23F_0.Size = size;
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox2.TabIndex = 163;
			this.PictureBox2.TabStop = false;
			this.Label5.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control arg_29C_0 = this.Label5;
			location = new global::System.Drawing.Point(154, 324);
			arg_29C_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_2C6_0 = this.Label5;
			size = new global::System.Drawing.Size(151, 13);
			arg_2C6_0.Size = size;
			this.Label5.TabIndex = 162;
			this.Label5.Text = "Mail Falan Yok Türkish";
			this.Label19.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.Label19.AutoSize = true;
			this.Label19.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold);
			global::System.Windows.Forms.Control arg_333_0 = this.Label19;
			location = new global::System.Drawing.Point(14, 324);
			arg_333_0.Location = location;
			this.Label19.Name = "Label19";
			global::System.Windows.Forms.Control arg_35A_0 = this.Label19;
			size = new global::System.Drawing.Size(52, 14);
			arg_35A_0.Size = size;
			this.Label19.TabIndex = 161;
			this.Label19.Text = "Contact:";
			this.Label22.AutoSize = true;
			this.Label22.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold);
			global::System.Windows.Forms.Control arg_3BB_0 = this.Label22;
			location = new global::System.Drawing.Point(14, 135);
			arg_3BB_0.Location = location;
			this.Label22.Name = "Label22";
			global::System.Windows.Forms.Control arg_3E2_0 = this.Label22;
			size = new global::System.Drawing.Size(93, 14);
			arg_3E2_0.Size = size;
			this.Label22.TabIndex = 158;
			this.Label22.Text = "DDoS  Stresser ";
			this.Label23.AutoSize = true;
			this.Label23.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold);
			global::System.Windows.Forms.Control arg_443_0 = this.Label23;
			location = new global::System.Drawing.Point(14, 201);
			arg_443_0.Location = location;
			this.Label23.Name = "Label23";
			global::System.Windows.Forms.Control arg_46A_0 = this.Label23;
			size = new global::System.Drawing.Size(94, 14);
			arg_46A_0.Size = size;
			this.Label23.TabIndex = 157;
			this.Label23.Text = "Server Detector";
			this.Panel6.Controls.Add(this.Label26);
			this.Panel6.Controls.Add(this.Button7);
			this.Panel6.Controls.Add(this.Button9);
			this.Panel6.Controls.Add(this.Button10);
			this.Panel6.Controls.Add(this.Button17);
			this.Panel6.Controls.Add(this.Button18);
			this.Panel6.Controls.Add(this.Label27);
			global::System.Windows.Forms.Control arg_53E_0 = this.Panel6;
			location = new global::System.Drawing.Point(395, 42);
			arg_53E_0.Location = location;
			this.Panel6.Name = "Panel6";
			global::System.Windows.Forms.Control arg_568_0 = this.Panel6;
			size = new global::System.Drawing.Size(115, 200);
			arg_568_0.Size = size;
			this.Panel6.TabIndex = 155;
			this.Label26.AutoSize = true;
			this.Label26.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Label26.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold | global::System.Drawing.FontStyle.Italic);
			global::System.Windows.Forms.Control arg_5C4_0 = this.Label26;
			location = new global::System.Drawing.Point(0, 187);
			arg_5C4_0.Location = location;
			this.Label26.Name = "Label26";
			global::System.Windows.Forms.Control arg_5EB_0 = this.Label26;
			size = new global::System.Drawing.Size(105, 13);
			arg_5EB_0.Size = size;
			this.Label26.TabIndex = 97;
			this.Label26.Text = "Ülkeyi Sömürdünüz Program Cracked";
			this.Button7.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button7.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button7.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button7.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button7.FlatAppearance.BorderSize = 0;
			this.Button7.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button7.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button7.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button7.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button7.Image");
			global::System.Windows.Forms.Control arg_6D6_0 = this.Button7;
			location = new global::System.Drawing.Point(0, 150);
			arg_6D6_0.Location = location;
			this.Button7.Name = "Button7";
			global::System.Windows.Forms.Control arg_6FD_0 = this.Button7;
			size = new global::System.Drawing.Size(115, 34);
			arg_6FD_0.Size = size;
			this.Button7.TabIndex = 93;
			this.Button7.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button7.UseVisualStyleBackColor = false;
			this.Button9.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button9.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button9.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button9.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button9.FlatAppearance.BorderSize = 0;
			this.Button9.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button9.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button9.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button9.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button9.Image");
			global::System.Windows.Forms.Control arg_7EE_0 = this.Button9;
			location = new global::System.Drawing.Point(0, 116);
			arg_7EE_0.Location = location;
			this.Button9.Name = "Button9";
			global::System.Windows.Forms.Control arg_815_0 = this.Button9;
			size = new global::System.Drawing.Size(115, 34);
			arg_815_0.Size = size;
			this.Button9.TabIndex = 91;
			this.Button9.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button9.UseVisualStyleBackColor = false;
			this.Button10.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button10.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button10.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button10.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button10.FlatAppearance.BorderSize = 0;
			this.Button10.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button10.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button10.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button10.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button10.Image");
			global::System.Windows.Forms.Control arg_906_0 = this.Button10;
			location = new global::System.Drawing.Point(0, 82);
			arg_906_0.Location = location;
			this.Button10.Name = "Button10";
			global::System.Windows.Forms.Control arg_92D_0 = this.Button10;
			size = new global::System.Drawing.Size(115, 34);
			arg_92D_0.Size = size;
			this.Button10.TabIndex = 90;
			this.Button10.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button10.UseVisualStyleBackColor = false;
			this.Button17.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button17.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button17.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button17.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button17.FlatAppearance.BorderSize = 0;
			this.Button17.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button17.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button17.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button17.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button17.Image");
			global::System.Windows.Forms.Control arg_A1E_0 = this.Button17;
			location = new global::System.Drawing.Point(0, 48);
			arg_A1E_0.Location = location;
			this.Button17.Name = "Button17";
			global::System.Windows.Forms.Control arg_A45_0 = this.Button17;
			size = new global::System.Drawing.Size(115, 34);
			arg_A45_0.Size = size;
			this.Button17.TabIndex = 89;
			this.Button17.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button17.UseVisualStyleBackColor = false;
			this.Button18.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button18.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button18.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button18.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button18.FlatAppearance.BorderSize = 0;
			this.Button18.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button18.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button18.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button18.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button18.Image");
			global::System.Windows.Forms.Control arg_B36_0 = this.Button18;
			location = new global::System.Drawing.Point(0, 14);
			arg_B36_0.Location = location;
			this.Button18.Name = "Button18";
			global::System.Windows.Forms.Control arg_B5D_0 = this.Button18;
			size = new global::System.Drawing.Size(115, 34);
			arg_B5D_0.Size = size;
			this.Button18.TabIndex = 88;
			this.Button18.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button18.UseVisualStyleBackColor = false;
			this.Label27.AutoSize = true;
			this.Label27.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label27.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold);
			global::System.Windows.Forms.Control arg_BCB_0 = this.Label27;
			location = new global::System.Drawing.Point(0, 0);
			arg_BCB_0.Location = location;
			this.Label27.Name = "Label27";
			global::System.Windows.Forms.Control arg_BF2_0 = this.Label27;
			size = new global::System.Drawing.Size(92, 14);
			arg_BF2_0.Size = size;
			this.Label27.TabIndex = 29;
			this.Label27.Text = "Ultimate Edition";
			this.Panel7.Controls.Add(this.Label28);
			this.Panel7.Controls.Add(this.Button25);
			this.Panel7.Controls.Add(this.Button27);
			this.Panel7.Controls.Add(this.Button28);
			this.Panel7.Controls.Add(this.Button29);
			this.Panel7.Controls.Add(this.Button30);
			this.Panel7.Controls.Add(this.Label29);
			global::System.Windows.Forms.Control arg_CC3_0 = this.Panel7;
			location = new global::System.Drawing.Point(274, 42);
			arg_CC3_0.Location = location;
			this.Panel7.Name = "Panel7";
			global::System.Windows.Forms.Control arg_CED_0 = this.Panel7;
			size = new global::System.Drawing.Size(115, 200);
			arg_CED_0.Size = size;
			this.Panel7.TabIndex = 154;
			this.Label28.AutoSize = true;
			this.Label28.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Label28.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold | global::System.Drawing.FontStyle.Italic);
			global::System.Windows.Forms.Control arg_D49_0 = this.Label28;
			location = new global::System.Drawing.Point(0, 187);
			arg_D49_0.Location = location;
			this.Label28.Name = "Label28";
			global::System.Windows.Forms.Control arg_D70_0 = this.Label28;
			size = new global::System.Drawing.Size(99, 13);
			arg_D70_0.Size = size;
			this.Label28.TabIndex = 97;
			this.Label28.Text = "Beleş diyorum Para diyorlar :P";
			this.Button25.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button25.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button25.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button25.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button25.FlatAppearance.BorderSize = 0;
			this.Button25.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button25.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button25.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button25.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button25.Image");
			global::System.Windows.Forms.Control arg_E5B_0 = this.Button25;
			location = new global::System.Drawing.Point(0, 150);
			arg_E5B_0.Location = location;
			this.Button25.Name = "Button25";
			global::System.Windows.Forms.Control arg_E82_0 = this.Button25;
			size = new global::System.Drawing.Size(115, 34);
			arg_E82_0.Size = size;
			this.Button25.TabIndex = 93;
			this.Button25.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button25.UseVisualStyleBackColor = false;
			this.Button27.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button27.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button27.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button27.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button27.FlatAppearance.BorderSize = 0;
			this.Button27.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button27.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button27.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button27.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button27.Image");
			global::System.Windows.Forms.Control arg_F73_0 = this.Button27;
			location = new global::System.Drawing.Point(0, 116);
			arg_F73_0.Location = location;
			this.Button27.Name = "Button27";
			global::System.Windows.Forms.Control arg_F9A_0 = this.Button27;
			size = new global::System.Drawing.Size(115, 34);
			arg_F9A_0.Size = size;
			this.Button27.TabIndex = 91;
			this.Button27.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button27.UseVisualStyleBackColor = false;
			this.Button28.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button28.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button28.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button28.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button28.FlatAppearance.BorderSize = 0;
			this.Button28.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button28.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button28.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button28.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button28.Image");
			global::System.Windows.Forms.Control arg_108B_0 = this.Button28;
			location = new global::System.Drawing.Point(0, 82);
			arg_108B_0.Location = location;
			this.Button28.Name = "Button28";
			global::System.Windows.Forms.Control arg_10B2_0 = this.Button28;
			size = new global::System.Drawing.Size(115, 34);
			arg_10B2_0.Size = size;
			this.Button28.TabIndex = 90;
			this.Button28.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button28.UseVisualStyleBackColor = false;
			this.Button29.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button29.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button29.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button29.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button29.FlatAppearance.BorderSize = 0;
			this.Button29.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button29.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button29.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button29.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button29.Image");
			global::System.Windows.Forms.Control arg_11A3_0 = this.Button29;
			location = new global::System.Drawing.Point(0, 48);
			arg_11A3_0.Location = location;
			this.Button29.Name = "Button29";
			global::System.Windows.Forms.Control arg_11CA_0 = this.Button29;
			size = new global::System.Drawing.Size(115, 34);
			arg_11CA_0.Size = size;
			this.Button29.TabIndex = 89;
			this.Button29.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button29.UseVisualStyleBackColor = false;
			this.Button30.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button30.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button30.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button30.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button30.FlatAppearance.BorderSize = 0;
			this.Button30.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button30.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button30.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button30.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button30.Image");
			global::System.Windows.Forms.Control arg_12BB_0 = this.Button30;
			location = new global::System.Drawing.Point(0, 14);
			arg_12BB_0.Location = location;
			this.Button30.Name = "Button30";
			global::System.Windows.Forms.Control arg_12E2_0 = this.Button30;
			size = new global::System.Drawing.Size(115, 34);
			arg_12E2_0.Size = size;
			this.Button30.TabIndex = 88;
			this.Button30.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button30.UseVisualStyleBackColor = false;
			this.Label29.AutoSize = true;
			this.Label29.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label29.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold);
			global::System.Windows.Forms.Control arg_1350_0 = this.Label29;
			location = new global::System.Drawing.Point(0, 0);
			arg_1350_0.Location = location;
			this.Label29.Name = "Label29";
			global::System.Windows.Forms.Control arg_1377_0 = this.Label29;
			size = new global::System.Drawing.Size(96, 14);
			arg_1377_0.Size = size;
			this.Label29.TabIndex = 29;
			this.Label29.Text = "Program Cracked :p";
			this.Panel8.Controls.Add(this.Label30);
			this.Panel8.Controls.Add(this.Button31);
			this.Panel8.Controls.Add(this.Button33);
			this.Panel8.Controls.Add(this.Button34);
			this.Panel8.Controls.Add(this.Button35);
			this.Panel8.Controls.Add(this.Button36);
			this.Panel8.Controls.Add(this.Label31);
			global::System.Windows.Forms.Control arg_1448_0 = this.Panel8;
			location = new global::System.Drawing.Point(153, 42);
			arg_1448_0.Location = location;
			this.Panel8.Name = "Panel8";
			global::System.Windows.Forms.Control arg_1472_0 = this.Panel8;
			size = new global::System.Drawing.Size(115, 200);
			arg_1472_0.Size = size;
			this.Panel8.TabIndex = 153;
			this.Label30.AutoSize = true;
			this.Label30.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Label30.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold | global::System.Drawing.FontStyle.Italic);
			global::System.Windows.Forms.Control arg_14CE_0 = this.Label30;
			location = new global::System.Drawing.Point(0, 187);
			arg_14CE_0.Location = location;
			this.Label30.Name = "Label30";
			global::System.Windows.Forms.Control arg_14F5_0 = this.Label30;
			size = new global::System.Drawing.Size(31, 13);
			arg_14F5_0.Size = size;
			this.Label30.TabIndex = 97;
			this.Label30.Text = "Free";
			this.Button31.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button31.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button31.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button31.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button31.FlatAppearance.BorderSize = 0;
			this.Button31.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button31.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button31.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button31.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button31.Image");
			global::System.Windows.Forms.Control arg_15E0_0 = this.Button31;
			location = new global::System.Drawing.Point(0, 150);
			arg_15E0_0.Location = location;
			this.Button31.Name = "Button31";
			global::System.Windows.Forms.Control arg_1607_0 = this.Button31;
			size = new global::System.Drawing.Size(115, 34);
			arg_1607_0.Size = size;
			this.Button31.TabIndex = 93;
			this.Button31.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button31.UseVisualStyleBackColor = false;
			this.Button33.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button33.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button33.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button33.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button33.FlatAppearance.BorderSize = 0;
			this.Button33.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button33.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button33.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button33.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button33.Image");
			global::System.Windows.Forms.Control arg_16F8_0 = this.Button33;
			location = new global::System.Drawing.Point(0, 116);
			arg_16F8_0.Location = location;
			this.Button33.Name = "Button33";
			global::System.Windows.Forms.Control arg_171F_0 = this.Button33;
			size = new global::System.Drawing.Size(115, 34);
			arg_171F_0.Size = size;
			this.Button33.TabIndex = 91;
			this.Button33.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button33.UseVisualStyleBackColor = false;
			this.Button34.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button34.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button34.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button34.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button34.FlatAppearance.BorderSize = 0;
			this.Button34.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button34.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button34.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button34.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button34.Image");
			global::System.Windows.Forms.Control arg_1810_0 = this.Button34;
			location = new global::System.Drawing.Point(0, 82);
			arg_1810_0.Location = location;
			this.Button34.Name = "Button34";
			global::System.Windows.Forms.Control arg_1837_0 = this.Button34;
			size = new global::System.Drawing.Size(115, 34);
			arg_1837_0.Size = size;
			this.Button34.TabIndex = 90;
			this.Button34.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button34.UseVisualStyleBackColor = false;
			this.Button35.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button35.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button35.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button35.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button35.FlatAppearance.BorderSize = 0;
			this.Button35.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button35.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button35.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button35.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button35.Image");
			global::System.Windows.Forms.Control arg_1928_0 = this.Button35;
			location = new global::System.Drawing.Point(0, 48);
			arg_1928_0.Location = location;
			this.Button35.Name = "Button35";
			global::System.Windows.Forms.Control arg_194F_0 = this.Button35;
			size = new global::System.Drawing.Size(115, 34);
			arg_194F_0.Size = size;
			this.Button35.TabIndex = 89;
			this.Button35.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button35.UseVisualStyleBackColor = false;
			this.Button36.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button36.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Button36.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button36.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button36.FlatAppearance.BorderSize = 0;
			this.Button36.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button36.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button36.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button36.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button36.Image");
			global::System.Windows.Forms.Control arg_1A40_0 = this.Button36;
			location = new global::System.Drawing.Point(0, 14);
			arg_1A40_0.Location = location;
			this.Button36.Name = "Button36";
			global::System.Windows.Forms.Control arg_1A67_0 = this.Button36;
			size = new global::System.Drawing.Size(115, 34);
			arg_1A67_0.Size = size;
			this.Button36.TabIndex = 88;
			this.Button36.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button36.UseVisualStyleBackColor = false;
			this.Label31.AutoSize = true;
			this.Label31.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label31.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold);
			global::System.Windows.Forms.Control arg_1AD5_0 = this.Label31;
			location = new global::System.Drawing.Point(0, 0);
			arg_1AD5_0.Location = location;
			this.Label31.Name = "Label31";
			global::System.Windows.Forms.Control arg_1AFC_0 = this.Label31;
			size = new global::System.Drawing.Size(72, 14);
			arg_1AFC_0.Size = size;
			this.Label31.TabIndex = 29;
			this.Label31.Text = "Free";
			this.Label32.AutoSize = true;
			this.Label32.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold);
			global::System.Windows.Forms.Control arg_1B57_0 = this.Label32;
			location = new global::System.Drawing.Point(14, 67);
			arg_1B57_0.Location = location;
			this.Label32.Name = "Label32";
			global::System.Windows.Forms.Control arg_1B7E_0 = this.Label32;
			size = new global::System.Drawing.Size(110, 14);
			arg_1B7E_0.Size = size;
			this.Label32.TabIndex = 150;
			this.Label32.Text = "Stored Passwords";
			this.Label33.AutoSize = true;
			this.Label33.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold);
			global::System.Windows.Forms.Control arg_1BDC_0 = this.Label33;
			location = new global::System.Drawing.Point(14, 101);
			arg_1BDC_0.Location = location;
			this.Label33.Name = "Label33";
			global::System.Windows.Forms.Control arg_1C03_0 = this.Label33;
			size = new global::System.Drawing.Size(78, 14);
			arg_1C03_0.Size = size;
			this.Label33.TabIndex = 151;
			this.Label33.Text = "Fun Manager";
			this.Label34.AutoSize = true;
			this.Label34.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold);
			global::System.Windows.Forms.Control arg_1C64_0 = this.Label34;
			location = new global::System.Drawing.Point(14, 169);
			arg_1C64_0.Location = location;
			this.Label34.Name = "Label34";
			global::System.Windows.Forms.Control arg_1C8B_0 = this.Label34;
			size = new global::System.Drawing.Size(81, 14);
			arg_1C8B_0.Size = size;
			this.Label34.TabIndex = 152;
			this.Label34.Text = "Plugin Server";
			this.GroupPanelBox1.Controls.Add(this.RichTextBox1);
			this.GroupPanelBox1.Controls.Add(this.RadioButton1);
			this.GroupPanelBox1.Controls.Add(this.RadioButton2);
			this.GroupPanelBox1.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.GroupPanelBox1.Font = new global::System.Drawing.Font("Arial", 8f);
			this.GroupPanelBox1.ForeColor = global::System.Drawing.Color.FromArgb(245, 245, 245);
			global::System.Windows.Forms.Control arg_1D4B_0 = this.GroupPanelBox1;
			location = new global::System.Drawing.Point(529, 0);
			arg_1D4B_0.Location = location;
			this.GroupPanelBox1.Name = "GroupPanelBox1";
			this.GroupPanelBox1.NoRounding = false;
			global::System.Windows.Forms.Control arg_1D84_0 = this.GroupPanelBox1;
			size = new global::System.Drawing.Size(238, 350);
			arg_1D84_0.Size = size;
			this.GroupPanelBox1.TabIndex = 170;
			this.GroupPanelBox1.Text = "No Buy";
			this.RichTextBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			global::System.Windows.Forms.Control arg_1DC8_0 = this.RichTextBox1;
			location = new global::System.Drawing.Point(18, 78);
			arg_1DC8_0.Location = location;
			this.RichTextBox1.Name = "RichTextBox1";
			global::System.Windows.Forms.Control arg_1DF5_0 = this.RichTextBox1;
			size = new global::System.Drawing.Size(208, 260);
			arg_1DF5_0.Size = size;
			this.RichTextBox1.TabIndex = 165;
			this.RichTextBox1.Text = componentResourceManager.GetString("RichTextBox1.Text");
			this.RadioButton1.AutoSize = true;
			global::System.Windows.Forms.Control arg_1E3E_0 = this.RadioButton1;
			location = new global::System.Drawing.Point(120, 38);
			arg_1E3E_0.Location = location;
			this.RadioButton1.Name = "RadioButton1";
			global::System.Windows.Forms.Control arg_1E65_0 = this.RadioButton1;
			size = new global::System.Drawing.Size(111, 18);
			arg_1E65_0.Size = size;
			this.RadioButton1.TabIndex = 166;
			this.RadioButton1.Text = "Bahasa Indonesia";
			this.RadioButton1.UseVisualStyleBackColor = true;
			this.RadioButton2.AutoSize = true;
			this.RadioButton2.Checked = true;
			global::System.Windows.Forms.Control arg_1EC0_0 = this.RadioButton2;
			location = new global::System.Drawing.Point(120, 53);
			arg_1EC0_0.Location = location;
			this.RadioButton2.Name = "RadioButton2";
			global::System.Windows.Forms.Control arg_1EE7_0 = this.RadioButton2;
			size = new global::System.Drawing.Size(59, 18);
			arg_1EE7_0.Size = size;
			this.RadioButton2.TabIndex = 167;
			this.RadioButton2.TabStop = true;
			this.RadioButton2.Text = "English";
			this.RadioButton2.UseVisualStyleBackColor = true;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.Black;
			size = new global::System.Drawing.Size(767, 350);
			this.ClientSize = size;
			this.Controls.Add(this.GroupPanelBox1);
			this.Controls.Add(this.PictureBox2);
			this.Controls.Add(this.Label5);
			this.Controls.Add(this.Label19);
			this.Controls.Add(this.Label22);
			this.Controls.Add(this.Label23);
			this.Controls.Add(this.Panel6);
			this.Controls.Add(this.Panel7);
			this.Controls.Add(this.Panel8);
			this.Controls.Add(this.Label32);
			this.Controls.Add(this.Label33);
			this.Controls.Add(this.Label34);
			this.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "FrmBuy";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Buy";
			this.TopMost = true;
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			this.Panel6.ResumeLayout(false);
			this.Panel6.PerformLayout();
			this.Panel7.ResumeLayout(false);
			this.Panel7.PerformLayout();
			this.Panel8.ResumeLayout(false);
			this.Panel8.PerformLayout();
			this.GroupPanelBox1.ResumeLayout(false);
			this.GroupPanelBox1.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x04000146 RID: 326
		private global::System.ComponentModel.IContainer components;
	}
}
