namespace NINGALINET
{
	// Token: 0x02000015 RID: 21
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class FrmFun : global::System.Windows.Forms.Form
	{
		// Token: 0x0600047C RID: 1148 RVA: 0x00028EB8 File Offset: 0x000270B8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600047D RID: 1149 RVA: 0x00028EFC File Offset: 0x000270FC
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::NINGALINET.FrmFun));
			this.Button38 = new global::System.Windows.Forms.Button();
			this.Button37 = new global::System.Windows.Forms.Button();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.TextBox7 = new global::System.Windows.Forms.TextBox();
			this.TextBox6 = new global::System.Windows.Forms.TextBox();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.ComboBox2 = new global::System.Windows.Forms.ComboBox();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.ComboBox3 = new global::System.Windows.Forms.ComboBox();
			this.NumericUpDown1 = new global::System.Windows.Forms.NumericUpDown();
			this.Button55 = new global::System.Windows.Forms.Button();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.PN1 = new global::System.Windows.Forms.Panel();
			this.PN2 = new global::System.Windows.Forms.Panel();
			this.GroupPanelBox2 = new global::NINGALINET.GroupPanelBox();
			this.Button36 = new global::System.Windows.Forms.Button();
			this.TextBox5 = new global::System.Windows.Forms.TextBox();
			this.Button34 = new global::System.Windows.Forms.Button();
			this.GroupPanelBox1 = new global::NINGALINET.GroupPanelBox();
			this.Button43 = new global::System.Windows.Forms.Button();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Button52 = new global::System.Windows.Forms.Button();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.TextBox3 = new global::System.Windows.Forms.TextBox();
			this.Check_Sound = new global::System.Windows.Forms.CheckBox();
			this.Button35 = new global::System.Windows.Forms.Button();
			this.Button48 = new global::System.Windows.Forms.Button();
			this.TextBox4 = new global::System.Windows.Forms.TextBox();
			this.Button40 = new global::System.Windows.Forms.Button();
			this.Button47 = new global::System.Windows.Forms.Button();
			this.Button49 = new global::System.Windows.Forms.Button();
			this.Button41 = new global::System.Windows.Forms.Button();
			this.Button46 = new global::System.Windows.Forms.Button();
			this.Button42 = new global::System.Windows.Forms.Button();
			this.Button50 = new global::System.Windows.Forms.Button();
			this.Button45 = new global::System.Windows.Forms.Button();
			this.Button51 = new global::System.Windows.Forms.Button();
			this.Button44 = new global::System.Windows.Forms.Button();
			this.Pn3 = new global::System.Windows.Forms.Panel();
			this.PN4 = new global::System.Windows.Forms.Panel();
			this.GroupDropBox6 = new global::NINGALINET.GroupDropBox();
			this.Button22 = new global::System.Windows.Forms.Button();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Button23 = new global::System.Windows.Forms.Button();
			this.TextBox2 = new global::System.Windows.Forms.TextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.GroupDropBox5 = new global::NINGALINET.GroupDropBox();
			this.Button21 = new global::System.Windows.Forms.Button();
			this.Button20 = new global::System.Windows.Forms.Button();
			this.Button19 = new global::System.Windows.Forms.Button();
			this.GroupDropBox4 = new global::NINGALINET.GroupDropBox();
			this.Button16 = new global::System.Windows.Forms.Button();
			this.Button15 = new global::System.Windows.Forms.Button();
			this.Button14 = new global::System.Windows.Forms.Button();
			this.Button10 = new global::System.Windows.Forms.Button();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.Button13 = new global::System.Windows.Forms.Button();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Button17 = new global::System.Windows.Forms.Button();
			this.Button9 = new global::System.Windows.Forms.Button();
			this.Button18 = new global::System.Windows.Forms.Button();
			this.GroupDropBox3 = new global::NINGALINET.GroupDropBox();
			this.Button29 = new global::System.Windows.Forms.Button();
			this.Button28 = new global::System.Windows.Forms.Button();
			this.Button33 = new global::System.Windows.Forms.Button();
			this.Button26 = new global::System.Windows.Forms.Button();
			this.Button32 = new global::System.Windows.Forms.Button();
			this.Button31 = new global::System.Windows.Forms.Button();
			this.Button11 = new global::System.Windows.Forms.Button();
			this.Button30 = new global::System.Windows.Forms.Button();
			this.Button12 = new global::System.Windows.Forms.Button();
			this.GroupDropBox2 = new global::NINGALINET.GroupDropBox();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.Button8 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.GroupDropBox1 = new global::NINGALINET.GroupDropBox();
			this.Button24 = new global::System.Windows.Forms.Button();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.Button25 = new global::System.Windows.Forms.Button();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.TabControl1 = new global::System.Windows.Forms.TabControl();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.TabPage3 = new global::System.Windows.Forms.TabPage();
			this.TabPage2 = new global::System.Windows.Forms.TabPage();
			this.TabPage4 = new global::System.Windows.Forms.TabPage();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.Button27 = new global::System.Windows.Forms.Button();
			this.Button39 = new global::System.Windows.Forms.Button();
			this.Button53 = new global::System.Windows.Forms.Button();
			this.Button54 = new global::System.Windows.Forms.Button();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown1).BeginInit();
			this.PN1.SuspendLayout();
			this.PN2.SuspendLayout();
			this.GroupPanelBox2.SuspendLayout();
			this.GroupPanelBox1.SuspendLayout();
			this.Pn3.SuspendLayout();
			this.PN4.SuspendLayout();
			this.GroupDropBox6.SuspendLayout();
			this.GroupDropBox5.SuspendLayout();
			this.GroupDropBox4.SuspendLayout();
			this.GroupDropBox3.SuspendLayout();
			this.GroupDropBox2.SuspendLayout();
			this.GroupDropBox1.SuspendLayout();
			this.TabControl1.SuspendLayout();
			this.TabPage1.SuspendLayout();
			this.TabPage3.SuspendLayout();
			this.TabPage2.SuspendLayout();
			this.TabPage4.SuspendLayout();
			this.Panel1.SuspendLayout();
			this.SuspendLayout();
			this.Button38.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button38.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Button38.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_565_0 = this.Button38;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 339);
			arg_565_0.Location = location;
			this.Button38.Name = "Button38";
			global::System.Windows.Forms.Control arg_58F_0 = this.Button38;
			global::System.Drawing.Size size = new global::System.Drawing.Size(585, 25);
			arg_58F_0.Size = size;
			this.Button38.TabIndex = 5;
			this.Button38.Text = "Test";
			this.Button38.UseVisualStyleBackColor = false;
			this.Button37.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button37.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Button37.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_5FE_0 = this.Button37;
			location = new global::System.Drawing.Point(0, 364);
			arg_5FE_0.Location = location;
			this.Button37.Name = "Button37";
			global::System.Windows.Forms.Control arg_628_0 = this.Button37;
			size = new global::System.Drawing.Size(585, 25);
			arg_628_0.Size = size;
			this.Button37.TabIndex = 3;
			this.Button37.Text = "Start";
			this.Button37.UseVisualStyleBackColor = false;
			this.Label6.AutoSize = true;
			global::System.Windows.Forms.Control arg_673_0 = this.Label6;
			location = new global::System.Drawing.Point(14, 41);
			arg_673_0.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control arg_69A_0 = this.Label6;
			size = new global::System.Drawing.Size(38, 14);
			arg_69A_0.Size = size;
			this.Label6.TabIndex = 4;
			this.Label6.Text = "Button";
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			global::System.Windows.Forms.Control arg_6EA_0 = this.PictureBox1;
			location = new global::System.Drawing.Point(261, 3);
			arg_6EA_0.Location = location;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control arg_711_0 = this.PictureBox1;
			size = new global::System.Drawing.Size(30, 32);
			arg_711_0.Size = size;
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.PictureBox1.TabIndex = 4;
			this.PictureBox1.TabStop = false;
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control arg_758_0 = this.Label5;
			location = new global::System.Drawing.Point(14, 12);
			arg_758_0.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control arg_77F_0 = this.Label5;
			size = new global::System.Drawing.Size(27, 14);
			arg_77F_0.Size = size;
			this.Label5.TabIndex = 3;
			this.Label5.Text = "Icon";
			this.TextBox7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.TextBox7.BackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.TextBox7.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox7.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			global::System.Windows.Forms.Control arg_7F0_0 = this.TextBox7;
			location = new global::System.Drawing.Point(5, 95);
			arg_7F0_0.Location = location;
			this.TextBox7.Multiline = true;
			this.TextBox7.Name = "TextBox7";
			global::System.Windows.Forms.Control arg_829_0 = this.TextBox7;
			size = new global::System.Drawing.Size(575, 238);
			arg_829_0.Size = size;
			this.TextBox7.TabIndex = 3;
			this.TextBox7.Text = "NGENET-RAT Cracked";
			this.TextBox6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.TextBox6.BackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.TextBox6.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox6.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			global::System.Windows.Forms.Control arg_89A_0 = this.TextBox6;
			location = new global::System.Drawing.Point(5, 67);
			arg_89A_0.Location = location;
			this.TextBox6.Name = "TextBox6";
			global::System.Windows.Forms.Control arg_8C4_0 = this.TextBox6;
			size = new global::System.Drawing.Size(575, 20);
			arg_8C4_0.Size = size;
			this.TextBox6.TabIndex = 2;
			this.TextBox6.Text = "...";
			this.ComboBox1.BackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.ComboBox1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.ComboBox1.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.ComboBox1.FormattingEnabled = true;
			this.ComboBox1.Items.AddRange(new object[]
			{
				"Information",
				"Question",
				"Warning",
				"Error"
			});
			global::System.Windows.Forms.Control arg_978_0 = this.ComboBox1;
			location = new global::System.Drawing.Point(62, 8);
			arg_978_0.Location = location;
			this.ComboBox1.Name = "ComboBox1";
			global::System.Windows.Forms.Control arg_9A2_0 = this.ComboBox1;
			size = new global::System.Drawing.Size(193, 22);
			arg_9A2_0.Size = size;
			this.ComboBox1.TabIndex = 0;
			this.ComboBox2.BackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.ComboBox2.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.ComboBox2.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.ComboBox2.FormattingEnabled = true;
			this.ComboBox2.Items.AddRange(new object[]
			{
				"Yes | No",
				"Yes | No| Cencel",
				"OK",
				"OK | Cencel",
				"Retry | Cencel",
				"Abort | Retry | Cencel"
			});
			global::System.Windows.Forms.Control arg_A57_0 = this.ComboBox2;
			location = new global::System.Drawing.Point(62, 38);
			arg_A57_0.Location = location;
			this.ComboBox2.Name = "ComboBox2";
			global::System.Windows.Forms.Control arg_A81_0 = this.ComboBox2;
			size = new global::System.Drawing.Size(193, 22);
			arg_A81_0.Size = size;
			this.ComboBox2.TabIndex = 1;
			this.PictureBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox2.BackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			global::System.Windows.Forms.Control arg_AC5_0 = this.PictureBox2;
			location = new global::System.Drawing.Point(5, 3);
			arg_AC5_0.Location = location;
			this.PictureBox2.Name = "PictureBox2";
			global::System.Windows.Forms.Control arg_AF2_0 = this.PictureBox2;
			size = new global::System.Drawing.Size(575, 327);
			arg_AF2_0.Size = size;
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox2.TabIndex = 0;
			this.PictureBox2.TabStop = false;
			this.Label7.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.Label7.AutoSize = true;
			this.Label7.Enabled = false;
			global::System.Windows.Forms.Control arg_B57_0 = this.Label7;
			location = new global::System.Drawing.Point(193, 342);
			arg_B57_0.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control arg_B7E_0 = this.Label7;
			size = new global::System.Drawing.Size(58, 14);
			arg_B7E_0.Size = size;
			this.Label7.TabIndex = 13;
			this.Label7.Text = "Second(s)";
			this.ComboBox3.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.ComboBox3.BackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.ComboBox3.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox3.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.ComboBox3.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.ComboBox3.FormattingEnabled = true;
			global::System.Windows.Forms.Control arg_C0B_0 = this.ComboBox3;
			location = new global::System.Drawing.Point(12, 336);
			arg_C0B_0.Location = location;
			this.ComboBox3.Name = "ComboBox3";
			global::System.Windows.Forms.Control arg_C32_0 = this.ComboBox3;
			size = new global::System.Drawing.Size(121, 22);
			arg_C32_0.Size = size;
			this.ComboBox3.TabIndex = 11;
			this.NumericUpDown1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.NumericUpDown1.BackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.NumericUpDown1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.NumericUpDown1.Enabled = false;
			this.NumericUpDown1.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			global::System.Windows.Forms.Control arg_CA6_0 = this.NumericUpDown1;
			location = new global::System.Drawing.Point(139, 337);
			arg_CA6_0.Location = location;
			this.NumericUpDown1.Name = "NumericUpDown1";
			global::System.Windows.Forms.Control arg_CCD_0 = this.NumericUpDown1;
			size = new global::System.Drawing.Size(48, 20);
			arg_CCD_0.Size = size;
			this.NumericUpDown1.TabIndex = 12;
			global::System.Windows.Forms.NumericUpDown arg_D0C_0 = this.NumericUpDown1;
			decimal value = new decimal(new int[]
			{
				8,
				0,
				0,
				0
			});
			arg_D0C_0.Value = value;
			this.Button55.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button55.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Button55.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_D53_0 = this.Button55;
			location = new global::System.Drawing.Point(0, 364);
			arg_D53_0.Location = location;
			this.Button55.Name = "Button55";
			global::System.Windows.Forms.Control arg_D7D_0 = this.Button55;
			size = new global::System.Drawing.Size(585, 25);
			arg_D7D_0.Size = size;
			this.Button55.TabIndex = 8;
			this.Button55.Text = "Start";
			this.Button55.UseVisualStyleBackColor = false;
			this.PN1.BackColor = global::System.Drawing.Color.Black;
			this.PN1.Controls.Add(this.PictureBox2);
			this.PN1.Controls.Add(this.Label7);
			this.PN1.Controls.Add(this.ComboBox3);
			this.PN1.Controls.Add(this.Button55);
			this.PN1.Controls.Add(this.NumericUpDown1);
			this.PN1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control arg_E44_0 = this.PN1;
			location = new global::System.Drawing.Point(3, 3);
			arg_E44_0.Location = location;
			this.PN1.Name = "PN1";
			global::System.Windows.Forms.Control arg_E71_0 = this.PN1;
			size = new global::System.Drawing.Size(585, 389);
			arg_E71_0.Size = size;
			this.PN1.TabIndex = 51;
			this.PN2.BackColor = global::System.Drawing.Color.Black;
			this.PN2.Controls.Add(this.GroupPanelBox2);
			this.PN2.Controls.Add(this.GroupPanelBox1);
			this.PN2.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control arg_EDB_0 = this.PN2;
			location = new global::System.Drawing.Point(3, 3);
			arg_EDB_0.Location = location;
			this.PN2.Name = "PN2";
			global::System.Windows.Forms.Control arg_F08_0 = this.PN2;
			size = new global::System.Drawing.Size(585, 389);
			arg_F08_0.Size = size;
			this.PN2.TabIndex = 52;
			this.GroupPanelBox2.Controls.Add(this.Button36);
			this.GroupPanelBox2.Controls.Add(this.TextBox5);
			this.GroupPanelBox2.Controls.Add(this.Button34);
			this.GroupPanelBox2.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.GroupPanelBox2.Font = new global::System.Drawing.Font("Arial", 8f);
			this.GroupPanelBox2.ForeColor = global::System.Drawing.Color.FromArgb(245, 245, 245);
			global::System.Windows.Forms.Control arg_FB5_0 = this.GroupPanelBox2;
			location = new global::System.Drawing.Point(0, 202);
			arg_FB5_0.Location = location;
			this.GroupPanelBox2.Name = "GroupPanelBox2";
			this.GroupPanelBox2.NoRounding = false;
			global::System.Windows.Forms.Control arg_FEE_0 = this.GroupPanelBox2;
			size = new global::System.Drawing.Size(585, 187);
			arg_FEE_0.Size = size;
			this.GroupPanelBox2.TabIndex = 49;
			this.GroupPanelBox2.Text = "Text To Speech";
			this.Button36.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button36.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Button36.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_1052_0 = this.Button36;
			location = new global::System.Drawing.Point(0, 137);
			arg_1052_0.Location = location;
			this.Button36.Name = "Button36";
			global::System.Windows.Forms.Control arg_107C_0 = this.Button36;
			size = new global::System.Drawing.Size(585, 25);
			arg_107C_0.Size = size;
			this.Button36.TabIndex = 2;
			this.Button36.Text = "Test";
			this.Button36.UseVisualStyleBackColor = false;
			this.TextBox5.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.TextBox5.BackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.TextBox5.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox5.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			global::System.Windows.Forms.Control arg_10F9_0 = this.TextBox5;
			location = new global::System.Drawing.Point(5, 34);
			arg_10F9_0.Location = location;
			this.TextBox5.Multiline = true;
			this.TextBox5.Name = "TextBox5";
			global::System.Windows.Forms.Control arg_112F_0 = this.TextBox5;
			size = new global::System.Drawing.Size(575, 97);
			arg_112F_0.Size = size;
			this.TextBox5.TabIndex = 0;
			this.TextBox5.Text = "WARNING!";
			this.Button34.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button34.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Button34.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_1192_0 = this.Button34;
			location = new global::System.Drawing.Point(0, 162);
			arg_1192_0.Location = location;
			this.Button34.Name = "Button34";
			global::System.Windows.Forms.Control arg_11BC_0 = this.Button34;
			size = new global::System.Drawing.Size(585, 25);
			arg_11BC_0.Size = size;
			this.Button34.TabIndex = 1;
			this.Button34.Text = "Start";
			this.Button34.UseVisualStyleBackColor = false;
			this.GroupPanelBox1.Controls.Add(this.Button43);
			this.GroupPanelBox1.Controls.Add(this.Label3);
			this.GroupPanelBox1.Controls.Add(this.Button52);
			this.GroupPanelBox1.Controls.Add(this.Label4);
			this.GroupPanelBox1.Controls.Add(this.TextBox3);
			this.GroupPanelBox1.Controls.Add(this.Check_Sound);
			this.GroupPanelBox1.Controls.Add(this.Button35);
			this.GroupPanelBox1.Controls.Add(this.Button48);
			this.GroupPanelBox1.Controls.Add(this.TextBox4);
			this.GroupPanelBox1.Controls.Add(this.Button40);
			this.GroupPanelBox1.Controls.Add(this.Button47);
			this.GroupPanelBox1.Controls.Add(this.Button49);
			this.GroupPanelBox1.Controls.Add(this.Button41);
			this.GroupPanelBox1.Controls.Add(this.Button46);
			this.GroupPanelBox1.Controls.Add(this.Button42);
			this.GroupPanelBox1.Controls.Add(this.Button50);
			this.GroupPanelBox1.Controls.Add(this.Button45);
			this.GroupPanelBox1.Controls.Add(this.Button51);
			this.GroupPanelBox1.Controls.Add(this.Button44);
			this.GroupPanelBox1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.GroupPanelBox1.Font = new global::System.Drawing.Font("Arial", 8f);
			this.GroupPanelBox1.ForeColor = global::System.Drawing.Color.FromArgb(245, 245, 245);
			global::System.Windows.Forms.Control arg_13E0_0 = this.GroupPanelBox1;
			location = new global::System.Drawing.Point(0, 0);
			arg_13E0_0.Location = location;
			this.GroupPanelBox1.Name = "GroupPanelBox1";
			this.GroupPanelBox1.NoRounding = false;
			global::System.Windows.Forms.Control arg_1419_0 = this.GroupPanelBox1;
			size = new global::System.Drawing.Size(585, 202);
			arg_1419_0.Size = size;
			this.GroupPanelBox1.TabIndex = 48;
			this.GroupPanelBox1.Text = "Piano";
			this.Button43.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Button43.BackColor = global::System.Drawing.Color.Transparent;
			this.Button43.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Button43.ForeColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1488_0 = this.Button43;
			location = new global::System.Drawing.Point(196, 36);
			arg_1488_0.Location = location;
			this.Button43.Name = "Button43";
			global::System.Windows.Forms.Control arg_14AF_0 = this.Button43;
			size = new global::System.Drawing.Size(30, 107);
			arg_14AF_0.Size = size;
			this.Button43.TabIndex = 30;
			this.Button43.UseVisualStyleBackColor = false;
			this.Label3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control arg_14FB_0 = this.Label3;
			location = new global::System.Drawing.Point(460, 99);
			arg_14FB_0.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control arg_1522_0 = this.Label3;
			size = new global::System.Drawing.Size(35, 14);
			arg_1522_0.Size = size;
			this.Label3.TabIndex = 1;
			this.Label3.Text = "Time :";
			this.Label3.Visible = false;
			this.Button52.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Button52.BackColor = global::System.Drawing.Color.Transparent;
			this.Button52.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Button52.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_159C_0 = this.Button52;
			location = new global::System.Drawing.Point(132, 36);
			arg_159C_0.Location = location;
			this.Button52.Name = "Button52";
			global::System.Windows.Forms.Control arg_15C6_0 = this.Button52;
			size = new global::System.Drawing.Size(40, 140);
			arg_15C6_0.Size = size;
			this.Button52.TabIndex = 20;
			this.Button52.UseVisualStyleBackColor = false;
			this.Label4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control arg_1612_0 = this.Label4;
			location = new global::System.Drawing.Point(460, 57);
			arg_1612_0.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control arg_1639_0 = this.Label4;
			size = new global::System.Drawing.Size(27, 14);
			arg_1639_0.Size = size;
			this.Label4.TabIndex = 1;
			this.Label4.Text = "HZ :";
			this.Label4.Visible = false;
			this.TextBox3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.TextBox3.BackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.TextBox3.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox3.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			global::System.Windows.Forms.Control arg_16BA_0 = this.TextBox3;
			location = new global::System.Drawing.Point(461, 116);
			arg_16BA_0.Location = location;
			this.TextBox3.Name = "TextBox3";
			global::System.Windows.Forms.Control arg_16E1_0 = this.TextBox3;
			size = new global::System.Drawing.Size(82, 20);
			arg_16E1_0.Size = size;
			this.TextBox3.TabIndex = 0;
			this.TextBox3.Text = "500";
			this.TextBox3.Visible = false;
			this.Check_Sound.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Check_Sound.AutoSize = true;
			global::System.Windows.Forms.Control arg_173E_0 = this.Check_Sound;
			location = new global::System.Drawing.Point(132, 182);
			arg_173E_0.Location = location;
			this.Check_Sound.Name = "Check_Sound";
			global::System.Windows.Forms.Control arg_1765_0 = this.Check_Sound;
			size = new global::System.Drawing.Size(52, 18);
			arg_1765_0.Size = size;
			this.Check_Sound.TabIndex = 16;
			this.Check_Sound.Text = "Client";
			this.Check_Sound.UseVisualStyleBackColor = true;
			this.Button35.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Button35.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button35.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_17DA_0 = this.Button35;
			location = new global::System.Drawing.Point(461, 142);
			arg_17DA_0.Location = location;
			this.Button35.Name = "Button35";
			global::System.Windows.Forms.Control arg_1801_0 = this.Button35;
			size = new global::System.Drawing.Size(82, 25);
			arg_1801_0.Size = size;
			this.Button35.TabIndex = 0;
			this.Button35.Text = "Start";
			this.Button35.UseVisualStyleBackColor = false;
			this.Button35.Visible = false;
			this.Button48.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Button48.BackColor = global::System.Drawing.Color.Transparent;
			this.Button48.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Button48.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_1887_0 = this.Button48;
			location = new global::System.Drawing.Point(288, 36);
			arg_1887_0.Location = location;
			this.Button48.Name = "Button48";
			global::System.Windows.Forms.Control arg_18B1_0 = this.Button48;
			size = new global::System.Drawing.Size(40, 140);
			arg_18B1_0.Size = size;
			this.Button48.TabIndex = 18;
			this.Button48.UseVisualStyleBackColor = false;
			this.TextBox4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.TextBox4.BackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.TextBox4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox4.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			global::System.Windows.Forms.Control arg_1923_0 = this.TextBox4;
			location = new global::System.Drawing.Point(461, 74);
			arg_1923_0.Location = location;
			this.TextBox4.Name = "TextBox4";
			global::System.Windows.Forms.Control arg_194A_0 = this.TextBox4;
			size = new global::System.Drawing.Size(82, 20);
			arg_194A_0.Size = size;
			this.TextBox4.TabIndex = 0;
			this.TextBox4.Text = "15000";
			this.TextBox4.Visible = false;
			this.Button40.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Button40.BackColor = global::System.Drawing.Color.Transparent;
			this.Button40.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Button40.ForeColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_19C4_0 = this.Button40;
			location = new global::System.Drawing.Point(351, 36);
			arg_19C4_0.Location = location;
			this.Button40.Name = "Button40";
			global::System.Windows.Forms.Control arg_19EB_0 = this.Button40;
			size = new global::System.Drawing.Size(30, 107);
			arg_19EB_0.Size = size;
			this.Button40.TabIndex = 26;
			this.Button40.UseVisualStyleBackColor = false;
			this.Button47.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Button47.BackColor = global::System.Drawing.Color.Transparent;
			this.Button47.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Button47.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_1A56_0 = this.Button47;
			location = new global::System.Drawing.Point(327, 36);
			arg_1A56_0.Location = location;
			this.Button47.Name = "Button47";
			global::System.Windows.Forms.Control arg_1A80_0 = this.Button47;
			size = new global::System.Drawing.Size(40, 140);
			arg_1A80_0.Size = size;
			this.Button47.TabIndex = 19;
			this.Button47.UseVisualStyleBackColor = false;
			this.Button49.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Button49.BackColor = global::System.Drawing.Color.Transparent;
			this.Button49.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Button49.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_1AEB_0 = this.Button49;
			location = new global::System.Drawing.Point(249, 36);
			arg_1AEB_0.Location = location;
			this.Button49.Name = "Button49";
			global::System.Windows.Forms.Control arg_1B15_0 = this.Button49;
			size = new global::System.Drawing.Size(40, 140);
			arg_1B15_0.Size = size;
			this.Button49.TabIndex = 17;
			this.Button49.UseVisualStyleBackColor = false;
			this.Button41.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Button41.BackColor = global::System.Drawing.Color.Transparent;
			this.Button41.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Button41.ForeColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1B80_0 = this.Button41;
			location = new global::System.Drawing.Point(312, 36);
			arg_1B80_0.Location = location;
			this.Button41.Name = "Button41";
			global::System.Windows.Forms.Control arg_1BA7_0 = this.Button41;
			size = new global::System.Drawing.Size(30, 107);
			arg_1BA7_0.Size = size;
			this.Button41.TabIndex = 25;
			this.Button41.UseVisualStyleBackColor = false;
			this.Button46.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Button46.BackColor = global::System.Drawing.Color.Transparent;
			this.Button46.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Button46.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_1C12_0 = this.Button46;
			location = new global::System.Drawing.Point(366, 36);
			arg_1C12_0.Location = location;
			this.Button46.Name = "Button46";
			global::System.Windows.Forms.Control arg_1C3C_0 = this.Button46;
			size = new global::System.Drawing.Size(40, 140);
			arg_1C3C_0.Size = size;
			this.Button46.TabIndex = 23;
			this.Button46.UseVisualStyleBackColor = false;
			this.Button42.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Button42.BackColor = global::System.Drawing.Color.Transparent;
			this.Button42.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Button42.ForeColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1CA7_0 = this.Button42;
			location = new global::System.Drawing.Point(273, 36);
			arg_1CA7_0.Location = location;
			this.Button42.Name = "Button42";
			global::System.Windows.Forms.Control arg_1CCE_0 = this.Button42;
			size = new global::System.Drawing.Size(30, 107);
			arg_1CCE_0.Size = size;
			this.Button42.TabIndex = 24;
			this.Button42.UseVisualStyleBackColor = false;
			this.Button50.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Button50.BackColor = global::System.Drawing.Color.Transparent;
			this.Button50.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Button50.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_1D39_0 = this.Button50;
			location = new global::System.Drawing.Point(210, 36);
			arg_1D39_0.Location = location;
			this.Button50.Name = "Button50";
			global::System.Windows.Forms.Control arg_1D63_0 = this.Button50;
			size = new global::System.Drawing.Size(40, 140);
			arg_1D63_0.Size = size;
			this.Button50.TabIndex = 22;
			this.Button50.UseVisualStyleBackColor = false;
			this.Button45.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Button45.BackColor = global::System.Drawing.Color.Transparent;
			this.Button45.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Button45.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_1DCE_0 = this.Button45;
			location = new global::System.Drawing.Point(405, 36);
			arg_1DCE_0.Location = location;
			this.Button45.Name = "Button45";
			global::System.Windows.Forms.Control arg_1DF8_0 = this.Button45;
			size = new global::System.Drawing.Size(40, 140);
			arg_1DF8_0.Size = size;
			this.Button45.TabIndex = 27;
			this.Button45.UseVisualStyleBackColor = false;
			this.Button51.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Button51.BackColor = global::System.Drawing.Color.Transparent;
			this.Button51.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Button51.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control arg_1E63_0 = this.Button51;
			location = new global::System.Drawing.Point(171, 36);
			arg_1E63_0.Location = location;
			this.Button51.Name = "Button51";
			global::System.Windows.Forms.Control arg_1E8D_0 = this.Button51;
			size = new global::System.Drawing.Size(40, 140);
			arg_1E8D_0.Size = size;
			this.Button51.TabIndex = 21;
			this.Button51.UseVisualStyleBackColor = false;
			this.Button44.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Button44.BackColor = global::System.Drawing.Color.Transparent;
			this.Button44.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Button44.ForeColor = global::System.Drawing.Color.Transparent;
			global::System.Windows.Forms.Control arg_1EF8_0 = this.Button44;
			location = new global::System.Drawing.Point(156, 36);
			arg_1EF8_0.Location = location;
			this.Button44.Name = "Button44";
			global::System.Windows.Forms.Control arg_1F1F_0 = this.Button44;
			size = new global::System.Drawing.Size(30, 107);
			arg_1F1F_0.Size = size;
			this.Button44.TabIndex = 28;
			this.Button44.UseVisualStyleBackColor = false;
			this.Pn3.BackColor = global::System.Drawing.Color.Black;
			this.Pn3.Controls.Add(this.Button38);
			this.Pn3.Controls.Add(this.Button37);
			this.Pn3.Controls.Add(this.Label5);
			this.Pn3.Controls.Add(this.Label6);
			this.Pn3.Controls.Add(this.ComboBox2);
			this.Pn3.Controls.Add(this.PictureBox1);
			this.Pn3.Controls.Add(this.ComboBox1);
			this.Pn3.Controls.Add(this.TextBox6);
			this.Pn3.Controls.Add(this.TextBox7);
			this.Pn3.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control arg_202F_0 = this.Pn3;
			location = new global::System.Drawing.Point(3, 3);
			arg_202F_0.Location = location;
			this.Pn3.Name = "Pn3";
			global::System.Windows.Forms.Control arg_205C_0 = this.Pn3;
			size = new global::System.Drawing.Size(585, 389);
			arg_205C_0.Size = size;
			this.Pn3.TabIndex = 53;
			this.PN4.AutoScroll = true;
			this.PN4.BackColor = global::System.Drawing.Color.Black;
			this.PN4.Controls.Add(this.GroupDropBox6);
			this.PN4.Controls.Add(this.GroupDropBox5);
			this.PN4.Controls.Add(this.GroupDropBox4);
			this.PN4.Controls.Add(this.GroupDropBox3);
			this.PN4.Controls.Add(this.GroupDropBox2);
			this.PN4.Controls.Add(this.GroupDropBox1);
			this.PN4.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control arg_212A_0 = this.PN4;
			location = new global::System.Drawing.Point(3, 3);
			arg_212A_0.Location = location;
			this.PN4.Name = "PN4";
			global::System.Windows.Forms.Control arg_2157_0 = this.PN4;
			size = new global::System.Drawing.Size(585, 389);
			arg_2157_0.Size = size;
			this.PN4.TabIndex = 54;
			this.GroupDropBox6.Checked = false;
			this.GroupDropBox6.Controls.Add(this.Button22);
			this.GroupDropBox6.Controls.Add(this.Label1);
			this.GroupDropBox6.Controls.Add(this.Button23);
			this.GroupDropBox6.Controls.Add(this.TextBox2);
			this.GroupDropBox6.Controls.Add(this.Label2);
			this.GroupDropBox6.Controls.Add(this.TextBox1);
			this.GroupDropBox6.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.GroupDropBox6.Font = new global::System.Drawing.Font("Arial", 8f);
			this.GroupDropBox6.ForeColor = global::System.Drawing.Color.FromArgb(245, 245, 245);
			global::System.Windows.Forms.Control arg_2252_0 = this.GroupDropBox6;
			location = new global::System.Drawing.Point(0, 150);
			arg_2252_0.Location = location;
			global::System.Windows.Forms.Control arg_2268_0 = this.GroupDropBox6;
			size = new global::System.Drawing.Size(5, 30);
			arg_2268_0.MinimumSize = size;
			this.GroupDropBox6.Name = "GroupDropBox6";
			this.GroupDropBox6.NoRounding = false;
			global::NINGALINET.GroupDropBox arg_22A1_0 = this.GroupDropBox6;
			size = new global::System.Drawing.Size(585, 130);
			arg_22A1_0.OpenSize = size;
			global::System.Windows.Forms.Control arg_22BB_0 = this.GroupDropBox6;
			size = new global::System.Drawing.Size(585, 30);
			arg_22BB_0.Size = size;
			this.GroupDropBox6.TabIndex = 50;
			this.GroupDropBox6.Text = "Webpage";
			this.Button22.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button22.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_2314_0 = this.Button22;
			location = new global::System.Drawing.Point(476, 57);
			arg_2314_0.Location = location;
			this.Button22.Name = "Button22";
			global::System.Windows.Forms.Control arg_233B_0 = this.Button22;
			size = new global::System.Drawing.Size(73, 25);
			arg_233B_0.Size = size;
			this.Button22.TabIndex = 3;
			this.Button22.Text = "Open";
			this.Button22.UseVisualStyleBackColor = false;
			this.Label1.AutoSize = true;
			global::System.Windows.Forms.Control arg_2386_0 = this.Label1;
			location = new global::System.Drawing.Point(14, 40);
			arg_2386_0.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control arg_23AD_0 = this.Label1;
			size = new global::System.Drawing.Size(75, 14);
			arg_23AD_0.Size = size;
			this.Label1.TabIndex = 1;
			this.Label1.Text = "Open Website";
			this.Button23.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button23.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_2405_0 = this.Button23;
			location = new global::System.Drawing.Point(476, 101);
			arg_2405_0.Location = location;
			this.Button23.Name = "Button23";
			global::System.Windows.Forms.Control arg_242C_0 = this.Button23;
			size = new global::System.Drawing.Size(73, 25);
			arg_242C_0.Size = size;
			this.Button23.TabIndex = 2;
			this.Button23.Text = "Done";
			this.Button23.UseVisualStyleBackColor = false;
			this.TextBox2.BackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.TextBox2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox2.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			global::System.Windows.Forms.Control arg_249D_0 = this.TextBox2;
			location = new global::System.Drawing.Point(17, 103);
			arg_249D_0.Location = location;
			this.TextBox2.Name = "TextBox2";
			global::System.Windows.Forms.Control arg_24C7_0 = this.TextBox2;
			size = new global::System.Drawing.Size(453, 20);
			arg_24C7_0.Size = size;
			this.TextBox2.TabIndex = 2;
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control arg_24F6_0 = this.Label2;
			location = new global::System.Drawing.Point(14, 85);
			arg_24F6_0.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control arg_251D_0 = this.Label2;
			size = new global::System.Drawing.Size(45, 14);
			arg_251D_0.Size = size;
			this.Label2.TabIndex = 3;
			this.Label2.Text = "IE Home";
			this.TextBox1.BackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.TextBox1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextBox1.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			global::System.Windows.Forms.Control arg_2582_0 = this.TextBox1;
			location = new global::System.Drawing.Point(17, 57);
			arg_2582_0.Location = location;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control arg_25AC_0 = this.TextBox1;
			size = new global::System.Drawing.Size(453, 20);
			arg_25AC_0.Size = size;
			this.TextBox1.TabIndex = 0;
			this.GroupDropBox5.Checked = false;
			this.GroupDropBox5.Controls.Add(this.Button21);
			this.GroupDropBox5.Controls.Add(this.Button20);
			this.GroupDropBox5.Controls.Add(this.Button19);
			this.GroupDropBox5.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.GroupDropBox5.Font = new global::System.Drawing.Font("Arial", 8f);
			this.GroupDropBox5.ForeColor = global::System.Drawing.Color.FromArgb(245, 245, 245);
			global::System.Windows.Forms.Control arg_2661_0 = this.GroupDropBox5;
			location = new global::System.Drawing.Point(0, 120);
			arg_2661_0.Location = location;
			global::System.Windows.Forms.Control arg_2677_0 = this.GroupDropBox5;
			size = new global::System.Drawing.Size(5, 30);
			arg_2677_0.MinimumSize = size;
			this.GroupDropBox5.Name = "GroupDropBox5";
			this.GroupDropBox5.NoRounding = false;
			global::NINGALINET.GroupDropBox arg_26AD_0 = this.GroupDropBox5;
			size = new global::System.Drawing.Size(585, 76);
			arg_26AD_0.OpenSize = size;
			global::System.Windows.Forms.Control arg_26C7_0 = this.GroupDropBox5;
			size = new global::System.Drawing.Size(585, 30);
			arg_26C7_0.Size = size;
			this.GroupDropBox5.TabIndex = 49;
			this.GroupDropBox5.Text = "Computer";
			this.Button21.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button21.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_271D_0 = this.Button21;
			location = new global::System.Drawing.Point(88, 41);
			arg_271D_0.Location = location;
			this.Button21.Name = "Button21";
			global::System.Windows.Forms.Control arg_2747_0 = this.Button21;
			size = new global::System.Drawing.Size(130, 25);
			arg_2747_0.Size = size;
			this.Button21.TabIndex = 36;
			this.Button21.Text = "Logoff";
			this.Button21.UseVisualStyleBackColor = false;
			this.Button20.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button20.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_27AC_0 = this.Button20;
			location = new global::System.Drawing.Point(224, 41);
			arg_27AC_0.Location = location;
			this.Button20.Name = "Button20";
			global::System.Windows.Forms.Control arg_27D6_0 = this.Button20;
			size = new global::System.Drawing.Size(130, 25);
			arg_27D6_0.Size = size;
			this.Button20.TabIndex = 37;
			this.Button20.Text = "Restart";
			this.Button20.UseVisualStyleBackColor = false;
			this.Button19.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button19.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_283B_0 = this.Button19;
			location = new global::System.Drawing.Point(360, 42);
			arg_283B_0.Location = location;
			this.Button19.Name = "Button19";
			global::System.Windows.Forms.Control arg_2865_0 = this.Button19;
			size = new global::System.Drawing.Size(130, 25);
			arg_2865_0.Size = size;
			this.Button19.TabIndex = 38;
			this.Button19.Text = "Shutdown";
			this.Button19.UseVisualStyleBackColor = false;
			this.GroupDropBox4.Checked = false;
			this.GroupDropBox4.Controls.Add(this.Button16);
			this.GroupDropBox4.Controls.Add(this.Button15);
			this.GroupDropBox4.Controls.Add(this.Button14);
			this.GroupDropBox4.Controls.Add(this.Button10);
			this.GroupDropBox4.Controls.Add(this.Button4);
			this.GroupDropBox4.Controls.Add(this.Button13);
			this.GroupDropBox4.Controls.Add(this.Button3);
			this.GroupDropBox4.Controls.Add(this.Button17);
			this.GroupDropBox4.Controls.Add(this.Button9);
			this.GroupDropBox4.Controls.Add(this.Button18);
			this.GroupDropBox4.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.GroupDropBox4.Font = new global::System.Drawing.Font("Arial", 8f);
			this.GroupDropBox4.ForeColor = global::System.Drawing.Color.FromArgb(245, 245, 245);
			global::System.Windows.Forms.Control arg_29D1_0 = this.GroupDropBox4;
			location = new global::System.Drawing.Point(0, 90);
			arg_29D1_0.Location = location;
			global::System.Windows.Forms.Control arg_29E7_0 = this.GroupDropBox4;
			size = new global::System.Drawing.Size(5, 30);
			arg_29E7_0.MinimumSize = size;
			this.GroupDropBox4.Name = "GroupDropBox4";
			this.GroupDropBox4.NoRounding = false;
			global::NINGALINET.GroupDropBox arg_2A20_0 = this.GroupDropBox4;
			size = new global::System.Drawing.Size(568, 140);
			arg_2A20_0.OpenSize = size;
			global::System.Windows.Forms.Control arg_2A3A_0 = this.GroupDropBox4;
			size = new global::System.Drawing.Size(585, 30);
			arg_2A3A_0.Size = size;
			this.GroupDropBox4.TabIndex = 48;
			this.GroupDropBox4.Text = "Enable/Disable";
			this.Button16.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button16.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_2A93_0 = this.Button16;
			location = new global::System.Drawing.Point(150, 41);
			arg_2A93_0.Location = location;
			this.Button16.Name = "Button16";
			global::System.Windows.Forms.Control arg_2ABD_0 = this.Button16;
			size = new global::System.Drawing.Size(130, 25);
			arg_2ABD_0.Size = size;
			this.Button16.TabIndex = 0;
			this.Button16.Text = "Disable Regedit";
			this.Button16.UseVisualStyleBackColor = false;
			this.Button15.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button15.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_2B1E_0 = this.Button15;
			location = new global::System.Drawing.Point(14, 41);
			arg_2B1E_0.Location = location;
			this.Button15.Name = "Button15";
			global::System.Windows.Forms.Control arg_2B48_0 = this.Button15;
			size = new global::System.Drawing.Size(130, 25);
			arg_2B48_0.Size = size;
			this.Button15.TabIndex = 1;
			this.Button15.Text = "Enable Regedit";
			this.Button15.UseVisualStyleBackColor = false;
			this.Button14.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button14.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_2BAC_0 = this.Button14;
			location = new global::System.Drawing.Point(150, 73);
			arg_2BAC_0.Location = location;
			this.Button14.Name = "Button14";
			global::System.Windows.Forms.Control arg_2BD6_0 = this.Button14;
			size = new global::System.Drawing.Size(130, 25);
			arg_2BD6_0.Size = size;
			this.Button14.TabIndex = 0;
			this.Button14.Text = "Disable cmd";
			this.Button14.UseVisualStyleBackColor = false;
			this.Button10.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button10.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_2C3A_0 = this.Button10;
			location = new global::System.Drawing.Point(421, 73);
			arg_2C3A_0.Location = location;
			this.Button10.Name = "Button10";
			global::System.Windows.Forms.Control arg_2C64_0 = this.Button10;
			size = new global::System.Drawing.Size(130, 25);
			arg_2C64_0.Size = size;
			this.Button10.TabIndex = 0;
			this.Button10.Text = "Disable Task Manager";
			this.Button10.UseVisualStyleBackColor = false;
			this.Button4.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button4.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_2CC8_0 = this.Button4;
			location = new global::System.Drawing.Point(285, 104);
			arg_2CC8_0.Location = location;
			this.Button4.Name = "Button4";
			global::System.Windows.Forms.Control arg_2CF2_0 = this.Button4;
			size = new global::System.Drawing.Size(130, 25);
			arg_2CF2_0.Size = size;
			this.Button4.TabIndex = 0;
			this.Button4.Text = "Disable Key+Mouse";
			this.Button4.UseVisualStyleBackColor = false;
			this.Button13.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button13.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_2D53_0 = this.Button13;
			location = new global::System.Drawing.Point(14, 73);
			arg_2D53_0.Location = location;
			this.Button13.Name = "Button13";
			global::System.Windows.Forms.Control arg_2D7D_0 = this.Button13;
			size = new global::System.Drawing.Size(130, 25);
			arg_2D7D_0.Size = size;
			this.Button13.TabIndex = 1;
			this.Button13.Text = "Enable cmd";
			this.Button13.UseVisualStyleBackColor = false;
			this.Button3.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button3.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_2DE1_0 = this.Button3;
			location = new global::System.Drawing.Point(149, 104);
			arg_2DE1_0.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control arg_2E0B_0 = this.Button3;
			size = new global::System.Drawing.Size(130, 25);
			arg_2E0B_0.Size = size;
			this.Button3.TabIndex = 1;
			this.Button3.Text = "Enable Key+Mouse";
			this.Button3.UseVisualStyleBackColor = false;
			this.Button17.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button17.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_2E6F_0 = this.Button17;
			location = new global::System.Drawing.Point(284, 41);
			arg_2E6F_0.Location = location;
			this.Button17.Name = "Button17";
			global::System.Windows.Forms.Control arg_2E99_0 = this.Button17;
			size = new global::System.Drawing.Size(130, 25);
			arg_2E99_0.Size = size;
			this.Button17.TabIndex = 1;
			this.Button17.Text = "Enable System Restore";
			this.Button17.UseVisualStyleBackColor = false;
			this.Button9.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button9.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_2EFD_0 = this.Button9;
			location = new global::System.Drawing.Point(285, 73);
			arg_2EFD_0.Location = location;
			this.Button9.Name = "Button9";
			global::System.Windows.Forms.Control arg_2F27_0 = this.Button9;
			size = new global::System.Drawing.Size(130, 25);
			arg_2F27_0.Size = size;
			this.Button9.TabIndex = 1;
			this.Button9.Text = "Enable Task Manager";
			this.Button9.UseVisualStyleBackColor = false;
			this.Button18.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button18.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_2F8B_0 = this.Button18;
			location = new global::System.Drawing.Point(420, 41);
			arg_2F8B_0.Location = location;
			this.Button18.Name = "Button18";
			global::System.Windows.Forms.Control arg_2FB5_0 = this.Button18;
			size = new global::System.Drawing.Size(130, 25);
			arg_2FB5_0.Size = size;
			this.Button18.TabIndex = 0;
			this.Button18.Text = "Disable System Restore";
			this.Button18.UseVisualStyleBackColor = false;
			this.GroupDropBox3.Checked = false;
			this.GroupDropBox3.Controls.Add(this.Button29);
			this.GroupDropBox3.Controls.Add(this.Button28);
			this.GroupDropBox3.Controls.Add(this.Button33);
			this.GroupDropBox3.Controls.Add(this.Button26);
			this.GroupDropBox3.Controls.Add(this.Button32);
			this.GroupDropBox3.Controls.Add(this.Button31);
			this.GroupDropBox3.Controls.Add(this.Button11);
			this.GroupDropBox3.Controls.Add(this.Button30);
			this.GroupDropBox3.Controls.Add(this.Button12);
			this.GroupDropBox3.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.GroupDropBox3.Font = new global::System.Drawing.Font("Arial", 8f);
			this.GroupDropBox3.ForeColor = global::System.Drawing.Color.FromArgb(245, 245, 245);
			global::System.Windows.Forms.Control arg_310A_0 = this.GroupDropBox3;
			location = new global::System.Drawing.Point(0, 60);
			arg_310A_0.Location = location;
			global::System.Windows.Forms.Control arg_3120_0 = this.GroupDropBox3;
			size = new global::System.Drawing.Size(5, 30);
			arg_3120_0.MinimumSize = size;
			this.GroupDropBox3.Name = "GroupDropBox3";
			this.GroupDropBox3.NoRounding = false;
			global::NINGALINET.GroupDropBox arg_3159_0 = this.GroupDropBox3;
			size = new global::System.Drawing.Size(568, 136);
			arg_3159_0.OpenSize = size;
			global::System.Windows.Forms.Control arg_3173_0 = this.GroupDropBox3;
			size = new global::System.Drawing.Size(585, 30);
			arg_3173_0.Size = size;
			this.GroupDropBox3.TabIndex = 47;
			this.GroupDropBox3.Text = "Hide/Show";
			this.Button29.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button29.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_31C9_0 = this.Button29;
			location = new global::System.Drawing.Point(14, 102);
			arg_31C9_0.Location = location;
			this.Button29.Name = "Button29";
			global::System.Windows.Forms.Control arg_31F3_0 = this.Button29;
			size = new global::System.Drawing.Size(130, 25);
			arg_31F3_0.Size = size;
			this.Button29.TabIndex = 29;
			this.Button29.Text = "Show Cursor";
			this.Button29.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button29.UseVisualStyleBackColor = false;
			this.Button28.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button28.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_3264_0 = this.Button28;
			location = new global::System.Drawing.Point(149, 102);
			arg_3264_0.Location = location;
			this.Button28.Name = "Button28";
			global::System.Windows.Forms.Control arg_328E_0 = this.Button28;
			size = new global::System.Drawing.Size(130, 25);
			arg_328E_0.Size = size;
			this.Button28.TabIndex = 28;
			this.Button28.Text = "Hide Cursor";
			this.Button28.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button28.UseVisualStyleBackColor = false;
			this.Button33.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button33.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_32FF_0 = this.Button33;
			location = new global::System.Drawing.Point(285, 102);
			arg_32FF_0.Location = location;
			this.Button33.Name = "Button33";
			global::System.Windows.Forms.Control arg_3329_0 = this.Button33;
			size = new global::System.Drawing.Size(130, 25);
			arg_3329_0.Size = size;
			this.Button33.TabIndex = 33;
			this.Button33.Text = "Show Clock";
			this.Button33.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button33.UseVisualStyleBackColor = false;
			this.Button26.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button26.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_3397_0 = this.Button26;
			location = new global::System.Drawing.Point(14, 40);
			arg_3397_0.Location = location;
			this.Button26.Name = "Button26";
			global::System.Windows.Forms.Control arg_33C1_0 = this.Button26;
			size = new global::System.Drawing.Size(536, 25);
			arg_33C1_0.Size = size;
			this.Button26.TabIndex = 26;
			this.Button26.Text = "Hide/Show Desktop Icons";
			this.Button26.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button26.UseVisualStyleBackColor = false;
			this.Button32.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button32.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_3432_0 = this.Button32;
			location = new global::System.Drawing.Point(420, 102);
			arg_3432_0.Location = location;
			this.Button32.Name = "Button32";
			global::System.Windows.Forms.Control arg_345C_0 = this.Button32;
			size = new global::System.Drawing.Size(130, 25);
			arg_345C_0.Size = size;
			this.Button32.TabIndex = 32;
			this.Button32.Text = "Hide Clock";
			this.Button32.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button32.UseVisualStyleBackColor = false;
			this.Button31.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button31.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_34CD_0 = this.Button31;
			location = new global::System.Drawing.Point(420, 71);
			arg_34CD_0.Location = location;
			this.Button31.Name = "Button31";
			global::System.Windows.Forms.Control arg_34F7_0 = this.Button31;
			size = new global::System.Drawing.Size(130, 25);
			arg_34F7_0.Size = size;
			this.Button31.TabIndex = 31;
			this.Button31.Text = "Hide Taskbar Icon";
			this.Button31.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button31.UseVisualStyleBackColor = false;
			this.Button11.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button11.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_3565_0 = this.Button11;
			location = new global::System.Drawing.Point(14, 71);
			arg_3565_0.Location = location;
			this.Button11.Name = "Button11";
			global::System.Windows.Forms.Control arg_358F_0 = this.Button11;
			size = new global::System.Drawing.Size(130, 25);
			arg_358F_0.Size = size;
			this.Button11.TabIndex = 1;
			this.Button11.Text = "Show Taskbar";
			this.Button11.UseVisualStyleBackColor = false;
			this.Button30.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button30.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_35F3_0 = this.Button30;
			location = new global::System.Drawing.Point(285, 71);
			arg_35F3_0.Location = location;
			this.Button30.Name = "Button30";
			global::System.Windows.Forms.Control arg_361D_0 = this.Button30;
			size = new global::System.Drawing.Size(130, 25);
			arg_361D_0.Size = size;
			this.Button30.TabIndex = 30;
			this.Button30.Text = "Show Taskbar Icon";
			this.Button30.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button30.UseVisualStyleBackColor = false;
			this.Button12.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button12.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_368E_0 = this.Button12;
			location = new global::System.Drawing.Point(149, 71);
			arg_368E_0.Location = location;
			this.Button12.Name = "Button12";
			global::System.Windows.Forms.Control arg_36B8_0 = this.Button12;
			size = new global::System.Drawing.Size(130, 25);
			arg_36B8_0.Size = size;
			this.Button12.TabIndex = 0;
			this.Button12.Text = "Hide Taskbar";
			this.Button12.UseVisualStyleBackColor = false;
			this.GroupDropBox2.Checked = false;
			this.GroupDropBox2.Controls.Add(this.Button7);
			this.GroupDropBox2.Controls.Add(this.Button8);
			this.GroupDropBox2.Controls.Add(this.Button2);
			this.GroupDropBox2.Controls.Add(this.Button1);
			this.GroupDropBox2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.GroupDropBox2.Font = new global::System.Drawing.Font("Arial", 8f);
			this.GroupDropBox2.ForeColor = global::System.Drawing.Color.FromArgb(245, 245, 245);
			global::System.Windows.Forms.Control arg_379F_0 = this.GroupDropBox2;
			location = new global::System.Drawing.Point(0, 30);
			arg_379F_0.Location = location;
			global::System.Windows.Forms.Control arg_37B5_0 = this.GroupDropBox2;
			size = new global::System.Drawing.Size(5, 30);
			arg_37B5_0.MinimumSize = size;
			this.GroupDropBox2.Name = "GroupDropBox2";
			this.GroupDropBox2.NoRounding = false;
			global::NINGALINET.GroupDropBox arg_37EB_0 = this.GroupDropBox2;
			size = new global::System.Drawing.Size(568, 71);
			arg_37EB_0.OpenSize = size;
			global::System.Windows.Forms.Control arg_3805_0 = this.GroupDropBox2;
			size = new global::System.Drawing.Size(585, 30);
			arg_3805_0.Size = size;
			this.GroupDropBox2.TabIndex = 46;
			this.GroupDropBox2.Text = "Function(s)";
			this.Button7.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button7.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_385B_0 = this.Button7;
			location = new global::System.Drawing.Point(14, 40);
			arg_385B_0.Location = location;
			this.Button7.Name = "Button7";
			global::System.Windows.Forms.Control arg_3885_0 = this.Button7;
			size = new global::System.Drawing.Size(130, 25);
			arg_3885_0.Size = size;
			this.Button7.TabIndex = 1;
			this.Button7.Text = "Mouse Revrse";
			this.Button7.UseVisualStyleBackColor = false;
			this.Button8.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button8.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_38E9_0 = this.Button8;
			location = new global::System.Drawing.Point(150, 40);
			arg_38E9_0.Location = location;
			this.Button8.Name = "Button8";
			global::System.Windows.Forms.Control arg_3913_0 = this.Button8;
			size = new global::System.Drawing.Size(130, 25);
			arg_3913_0.Size = size;
			this.Button8.TabIndex = 0;
			this.Button8.Text = "Mouse Normal";
			this.Button8.UseVisualStyleBackColor = false;
			this.Button2.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button2.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_3977_0 = this.Button2;
			location = new global::System.Drawing.Point(422, 40);
			arg_3977_0.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control arg_39A1_0 = this.Button2;
			size = new global::System.Drawing.Size(130, 25);
			arg_39A1_0.Size = size;
			this.Button2.TabIndex = 1;
			this.Button2.Text = "Close CD";
			this.Button2.UseVisualStyleBackColor = false;
			this.Button1.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_3A05_0 = this.Button1;
			location = new global::System.Drawing.Point(286, 40);
			arg_3A05_0.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control arg_3A2F_0 = this.Button1;
			size = new global::System.Drawing.Size(130, 25);
			arg_3A2F_0.Size = size;
			this.Button1.TabIndex = 0;
			this.Button1.Text = "Open CD";
			this.Button1.UseVisualStyleBackColor = false;
			this.GroupDropBox1.Checked = false;
			this.GroupDropBox1.Controls.Add(this.Button24);
			this.GroupDropBox1.Controls.Add(this.Button6);
			this.GroupDropBox1.Controls.Add(this.Button25);
			this.GroupDropBox1.Controls.Add(this.Button5);
			this.GroupDropBox1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.GroupDropBox1.Font = new global::System.Drawing.Font("Arial", 8f);
			this.GroupDropBox1.ForeColor = global::System.Drawing.Color.FromArgb(245, 245, 245);
			global::System.Windows.Forms.Control arg_3B15_0 = this.GroupDropBox1;
			location = new global::System.Drawing.Point(0, 0);
			arg_3B15_0.Location = location;
			global::System.Windows.Forms.Control arg_3B2B_0 = this.GroupDropBox1;
			size = new global::System.Drawing.Size(5, 30);
			arg_3B2B_0.MinimumSize = size;
			this.GroupDropBox1.Name = "GroupDropBox1";
			this.GroupDropBox1.NoRounding = false;
			global::NINGALINET.GroupDropBox arg_3B61_0 = this.GroupDropBox1;
			size = new global::System.Drawing.Size(568, 71);
			arg_3B61_0.OpenSize = size;
			global::System.Windows.Forms.Control arg_3B7B_0 = this.GroupDropBox1;
			size = new global::System.Drawing.Size(585, 30);
			arg_3B7B_0.Size = size;
			this.GroupDropBox1.TabIndex = 45;
			this.GroupDropBox1.Text = "ON/OFF";
			this.Button24.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button24.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_3BD4_0 = this.Button24;
			location = new global::System.Drawing.Point(420, 38);
			arg_3BD4_0.Location = location;
			this.Button24.Name = "Button24";
			global::System.Windows.Forms.Control arg_3BFE_0 = this.Button24;
			size = new global::System.Drawing.Size(130, 25);
			arg_3BFE_0.Size = size;
			this.Button24.TabIndex = 34;
			this.Button24.Text = "Sound OFF";
			this.Button24.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button24.UseVisualStyleBackColor = false;
			this.Button6.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button6.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_3C6C_0 = this.Button6;
			location = new global::System.Drawing.Point(13, 38);
			arg_3C6C_0.Location = location;
			this.Button6.Name = "Button6";
			global::System.Windows.Forms.Control arg_3C96_0 = this.Button6;
			size = new global::System.Drawing.Size(130, 25);
			arg_3C96_0.Size = size;
			this.Button6.TabIndex = 0;
			this.Button6.Text = "Monitor ON";
			this.Button6.UseVisualStyleBackColor = false;
			this.Button25.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button25.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_3CFA_0 = this.Button25;
			location = new global::System.Drawing.Point(284, 38);
			arg_3CFA_0.Location = location;
			this.Button25.Name = "Button25";
			global::System.Windows.Forms.Control arg_3D24_0 = this.Button25;
			size = new global::System.Drawing.Size(130, 25);
			arg_3D24_0.Size = size;
			this.Button25.TabIndex = 35;
			this.Button25.Text = "Sound ON";
			this.Button25.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button25.UseVisualStyleBackColor = false;
			this.Button5.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.Button5.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			global::System.Windows.Forms.Control arg_3D95_0 = this.Button5;
			location = new global::System.Drawing.Point(148, 38);
			arg_3D95_0.Location = location;
			this.Button5.Name = "Button5";
			global::System.Windows.Forms.Control arg_3DBF_0 = this.Button5;
			size = new global::System.Drawing.Size(130, 25);
			arg_3DBF_0.Size = size;
			this.Button5.TabIndex = 1;
			this.Button5.Text = "Monitor OFF";
			this.Button5.UseVisualStyleBackColor = false;
			this.TabControl1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.TabControl1.Controls.Add(this.TabPage1);
			this.TabControl1.Controls.Add(this.TabPage4);
			this.TabControl1.Controls.Add(this.TabPage2);
			this.TabControl1.Controls.Add(this.TabPage3);
			global::System.Windows.Forms.Control arg_3E62_0 = this.TabControl1;
			location = new global::System.Drawing.Point(-7, 8);
			arg_3E62_0.Location = location;
			this.TabControl1.Name = "TabControl1";
			this.TabControl1.SelectedIndex = 0;
			global::System.Windows.Forms.Control arg_3E9B_0 = this.TabControl1;
			size = new global::System.Drawing.Size(599, 422);
			arg_3E9B_0.Size = size;
			this.TabControl1.TabIndex = 56;
			this.TabPage1.Controls.Add(this.PN4);
			global::System.Windows.Forms.TabPage arg_3ED4_0 = this.TabPage1;
			location = new global::System.Drawing.Point(4, 23);
			arg_3ED4_0.Location = location;
			this.TabPage1.Name = "TabPage1";
			global::System.Windows.Forms.Control arg_3EF9_0 = this.TabPage1;
			global::System.Windows.Forms.Padding padding = new global::System.Windows.Forms.Padding(3);
			arg_3EF9_0.Padding = padding;
			global::System.Windows.Forms.Control arg_3F16_0 = this.TabPage1;
			size = new global::System.Drawing.Size(591, 395);
			arg_3F16_0.Size = size;
			this.TabPage1.TabIndex = 0;
			this.TabPage1.Text = "TabPage1";
			this.TabPage1.UseVisualStyleBackColor = true;
			this.TabPage3.Controls.Add(this.PN2);
			global::System.Windows.Forms.TabPage arg_3F6A_0 = this.TabPage3;
			location = new global::System.Drawing.Point(4, 23);
			arg_3F6A_0.Location = location;
			this.TabPage3.Name = "TabPage3";
			global::System.Windows.Forms.Control arg_3F8F_0 = this.TabPage3;
			padding = new global::System.Windows.Forms.Padding(3);
			arg_3F8F_0.Padding = padding;
			global::System.Windows.Forms.Control arg_3FAC_0 = this.TabPage3;
			size = new global::System.Drawing.Size(591, 395);
			arg_3FAC_0.Size = size;
			this.TabPage3.TabIndex = 2;
			this.TabPage3.Text = "TabPage3";
			this.TabPage3.UseVisualStyleBackColor = true;
			this.TabPage2.Controls.Add(this.PN1);
			global::System.Windows.Forms.TabPage arg_4000_0 = this.TabPage2;
			location = new global::System.Drawing.Point(4, 23);
			arg_4000_0.Location = location;
			this.TabPage2.Name = "TabPage2";
			global::System.Windows.Forms.Control arg_4025_0 = this.TabPage2;
			padding = new global::System.Windows.Forms.Padding(3);
			arg_4025_0.Padding = padding;
			global::System.Windows.Forms.Control arg_4042_0 = this.TabPage2;
			size = new global::System.Drawing.Size(591, 395);
			arg_4042_0.Size = size;
			this.TabPage2.TabIndex = 1;
			this.TabPage2.Text = "TabPage2";
			this.TabPage2.UseVisualStyleBackColor = true;
			this.TabPage4.Controls.Add(this.Pn3);
			global::System.Windows.Forms.TabPage arg_4096_0 = this.TabPage4;
			location = new global::System.Drawing.Point(4, 23);
			arg_4096_0.Location = location;
			this.TabPage4.Name = "TabPage4";
			global::System.Windows.Forms.Control arg_40BB_0 = this.TabPage4;
			padding = new global::System.Windows.Forms.Padding(3);
			arg_40BB_0.Padding = padding;
			global::System.Windows.Forms.Control arg_40D8_0 = this.TabPage4;
			size = new global::System.Drawing.Size(591, 395);
			arg_40D8_0.Size = size;
			this.TabPage4.TabIndex = 3;
			this.TabPage4.Text = "TabPage4";
			this.TabPage4.UseVisualStyleBackColor = true;
			this.Panel1.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Panel1.Controls.Add(this.Button27);
			this.Panel1.Controls.Add(this.Button39);
			this.Panel1.Controls.Add(this.Button53);
			this.Panel1.Controls.Add(this.Button54);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			global::System.Windows.Forms.Control arg_418F_0 = this.Panel1;
			location = new global::System.Drawing.Point(0, 0);
			arg_418F_0.Location = location;
			this.Panel1.Name = "Panel1";
			global::System.Windows.Forms.Control arg_41B9_0 = this.Panel1;
			size = new global::System.Drawing.Size(584, 32);
			arg_41B9_0.Size = size;
			this.Panel1.TabIndex = 57;
			this.Button27.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button27.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Button27.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button27.FlatAppearance.BorderSize = 0;
			this.Button27.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.Button27.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.Button27.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button27.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button27.Image");
			this.Button27.ImageAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			global::System.Windows.Forms.Control arg_428B_0 = this.Button27;
			location = new global::System.Drawing.Point(279, 0);
			arg_428B_0.Location = location;
			this.Button27.Name = "Button27";
			global::System.Windows.Forms.Control arg_42B2_0 = this.Button27;
			size = new global::System.Drawing.Size(101, 32);
			arg_42B2_0.Size = size;
			this.Button27.TabIndex = 45;
			this.Button27.Text = "MessageBox";
			this.Button27.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button27.UseVisualStyleBackColor = false;
			this.Button39.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button39.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Button39.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button39.FlatAppearance.BorderSize = 0;
			this.Button39.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.Button39.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.Button39.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button39.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button39.Image");
			this.Button39.ImageAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			global::System.Windows.Forms.Control arg_43AD_0 = this.Button39;
			location = new global::System.Drawing.Point(178, 0);
			arg_43AD_0.Location = location;
			this.Button39.Name = "Button39";
			global::System.Windows.Forms.Control arg_43D4_0 = this.Button39;
			size = new global::System.Drawing.Size(101, 32);
			arg_43D4_0.Size = size;
			this.Button39.TabIndex = 44;
			this.Button39.Text = "Piano-Speech";
			this.Button39.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button39.UseVisualStyleBackColor = false;
			this.Button53.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button53.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Button53.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button53.FlatAppearance.BorderSize = 0;
			this.Button53.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.Button53.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.Button53.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button53.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button53.Image");
			this.Button53.ImageAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			global::System.Windows.Forms.Control arg_44CC_0 = this.Button53;
			location = new global::System.Drawing.Point(102, 0);
			arg_44CC_0.Location = location;
			this.Button53.Name = "Button53";
			global::System.Windows.Forms.Control arg_44F3_0 = this.Button53;
			size = new global::System.Drawing.Size(76, 32);
			arg_44F3_0.Size = size;
			this.Button53.TabIndex = 43;
			this.Button53.Tag = "0";
			this.Button53.Text = "Horror";
			this.Button53.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button53.UseVisualStyleBackColor = false;
			this.Button54.BackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.Button54.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button54.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Button54.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button54.FlatAppearance.BorderSize = 0;
			this.Button54.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.Button54.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			this.Button54.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button54.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button54.Image");
			this.Button54.ImageAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			global::System.Windows.Forms.Control arg_4610_0 = this.Button54;
			location = new global::System.Drawing.Point(0, 0);
			arg_4610_0.Location = location;
			this.Button54.Name = "Button54";
			global::System.Windows.Forms.Control arg_4637_0 = this.Button54;
			size = new global::System.Drawing.Size(102, 32);
			arg_4637_0.Size = size;
			this.Button54.TabIndex = 42;
			this.Button54.Tag = "0";
			this.Button54.Text = "Fun Functions";
			this.Button54.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Button54.UseVisualStyleBackColor = false;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 14f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.Black;
			size = new global::System.Drawing.Size(584, 423);
			this.ClientSize = size;
			this.Controls.Add(this.Panel1);
			this.Controls.Add(this.TabControl1);
			this.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ForeColor = global::System.Drawing.Color.WhiteSmoke;
			this.Name = "FrmFun";
			this.ShowIcon = false;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Fun - ";
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.NumericUpDown1).EndInit();
			this.PN1.ResumeLayout(false);
			this.PN1.PerformLayout();
			this.PN2.ResumeLayout(false);
			this.GroupPanelBox2.ResumeLayout(false);
			this.GroupPanelBox2.PerformLayout();
			this.GroupPanelBox1.ResumeLayout(false);
			this.GroupPanelBox1.PerformLayout();
			this.Pn3.ResumeLayout(false);
			this.Pn3.PerformLayout();
			this.PN4.ResumeLayout(false);
			this.GroupDropBox6.ResumeLayout(false);
			this.GroupDropBox6.PerformLayout();
			this.GroupDropBox5.ResumeLayout(false);
			this.GroupDropBox4.ResumeLayout(false);
			this.GroupDropBox3.ResumeLayout(false);
			this.GroupDropBox2.ResumeLayout(false);
			this.GroupDropBox1.ResumeLayout(false);
			this.TabControl1.ResumeLayout(false);
			this.TabPage1.ResumeLayout(false);
			this.TabPage3.ResumeLayout(false);
			this.TabPage2.ResumeLayout(false);
			this.TabPage4.ResumeLayout(false);
			this.Panel1.ResumeLayout(false);
			this.ResumeLayout(false);
		}

		// Token: 0x0400021C RID: 540
		private global::System.ComponentModel.IContainer components;
	}
}
